-- MySQL Script generated by MySQL Workbench
-- Sun Nov 10 18:46:41 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema flask_api_dev
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema flask_api_dev
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `flask_api_dev` DEFAULT CHARACTER SET utf8mb4 ;
USE `flask_api_dev` ;

-- -----------------------------------------------------
-- Table `flask_api_dev`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flask_api_dev`.`users` (
  `user_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `login` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) ,
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flask_api_dev`.`dishes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flask_api_dev`.`dishes` (
  `dish_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`dish_id`),
  UNIQUE INDEX `dish_id_UNIQUE` (`dish_id` ASC) ,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flask_api_dev`.`user_past_dishes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flask_api_dev`.`user_past_dishes` (
  `user_past_dish_id` INT NOT NULL,
  `eat_time` INT NULL,
  `quantity` INT NULL,
  `users_user_id` INT NOT NULL,
  `dishes_dish_id` INT NOT NULL,
  PRIMARY KEY (`user_past_dish_id`),
  UNIQUE INDEX `user_past_dish_id_UNIQUE` (`user_past_dish_id` ASC) ,
  INDEX `fk_user_past_dishes_users_idx` (`users_user_id` ASC) ,
  INDEX `fk_user_past_dishes_dishes1_idx` (`dishes_dish_id` ASC) ,
  CONSTRAINT `fk_user_past_dishes_users`
    FOREIGN KEY (`users_user_id`)
    REFERENCES `flask_api_dev`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_past_dishes_dishes1`
    FOREIGN KEY (`dishes_dish_id`)
    REFERENCES `flask_api_dev`.`dishes` (`dish_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flask_api_dev`.`user_tastes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flask_api_dev`.`user_tastes` (
  `taste_id` INT NOT NULL,
  `rating` INT NOT NULL,
  `users_user_id` INT NOT NULL,
  `dishes_dish_id` INT NOT NULL,
  PRIMARY KEY (`taste_id`),
  UNIQUE INDEX `taste_id_UNIQUE` (`taste_id` ASC) ,
  INDEX `fk_users_tastes_users1_idx` (`users_user_id` ASC) ,
  INDEX `fk_user_tastes_dishes1_idx` (`dishes_dish_id` ASC) ,
  CONSTRAINT `fk_users_tastes_users1`
    FOREIGN KEY (`users_user_id`)
    REFERENCES `flask_api_dev`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_tastes_dishes1`
    FOREIGN KEY (`dishes_dish_id`)
    REFERENCES `flask_api_dev`.`dishes` (`dish_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
